export const HOST = 'chvbdq.herokuapp.com';
export const PORT = '443';

//home: fetch_products
export const HOME_CHANGE_CATEGORY = 'HOME_CHANGE_CATEGORY';
export const HOME_FETCH_PRODUCT_SUCCESS = 'HOME_FETCH_PRODUCT_SUCCESS';
// login
export const LOGIN = "LOGIN";
export const REMEMBER_LOGIN = "REMEMBER_LOGIN";
// register
export const REGISTER = "REGISTER";
// employee
export const EMPLOYEE_CHANGE_CATEGORY = "EMPLOYEE_CHANGE_CATEGORY";
export const EMPLOYEE_FETCH_LISTITEM_SUCCESS = "EMPLOYEE_FETCH_LISTITEM_SUCCESS";
// search
export const FETCH_SEARCH_RESULT = 'FETCH_SEARCH_RESULT';
// products
export const PRODUCTS_FETCH_LIST_SUCCESS = "PRODUCTS_FETCH_LIST_SUCCESS";
export const PRODUCTS_FETCH_LIST_LOADING = "PRODUCTS_FETCH_LIST_LOADING";
export const PRODUCTS_FETCH_LIST_FAILED = "PRODUCTS_FETCH_LIST_FAILED";
export const PRODUCTS_CHANGE_SELECTED_PRODUCT = "PRODUCTS_CHANGE_SELECTED_PRODUCT";

export const PRODUCTS_ADD_PRODUCT_SUCCESS = "PRODUCTS_ADD_PRODUCT_SUCCESS";
export const PRODUCTS_ADD_PRODUCT_FAILED = "PRODUCTS_ADD_PRODUCT_FAILED";

export const PRODUCTS_LIST_CHANGED = "PRODUCTS_LIST_CHANGED";

// employee
export const EMPLOYEES_FETCH_LIST_SUCCESS = "EMPLOYEES_FETCH_LIST_SUCCESS";
export const EMPLOYEES_FETCH_LIST_LOADING = "EMPLOYEES_FETCH_LIST_LOADING";
export const EMPLOYEES_FETCH_LIST_FAILED = "EMPLOYEES_FETCH_LIST_FAILED";
export const EMPLOYEES_CHANGE_SELECTED_EMPLOYEE = "EMPLOYEES_CHANGE_SELECTED_EMPLOYEE";

export const EMPLOYEES_ADD_EMPLOYEE_SUCCESS = "EMPLOYEES_ADD_EMPLOYEE_SUCCESS";
export const EMPLOYEES_ADD_EMPLOYEE_FAILED = "EMPLOYEES_ADD_EMPLOYEE_FAILED";

export const EMPLOYEES_LIST_CHANGED = "EMPLOYEES_LIST_CHANGED";