export const HOST = 'chvbdq.herokuapp.com';
export const PORT = '443';

//home: fetch_products
export const HOME_CHANGE_CATEGORY = 'HOME_CHANGE_CATEGORY';
export const HOME_FETCH_PRODUCT_SUCCESS = 'HOME_FETCH_PRODUCT_SUCCESS';
// login
export const LOGIN = "LOGIN";
export const REMEMBER_LOGIN = "REMEMBER_LOGIN";
// register
export const REGISTER = "REGISTER";
// employee
export const EMPLOYEE_CHANGE_CATEGORY = "EMPLOYEE_CHANGE_CATEGORY";
export const EMPLOYEE_FETCH_LISTITEM_SUCCESS = "EMPLOYEE_FETCH_LISTITEM_SUCCESS";
// search
export const FETCH_SEARCH_RESULT = 'FETCH_SEARCH_RESULT';
// products
export const PRODUCTS_FETCH_LIST_SUCCESS = "PRODUCTS_FETCH_LIST_SUCCESS";
export const PRODUCTS_FETCH_LIST_LOADING = "PRODUCTS_FETCH_LIST_LOADING";
export const PRODUCTS_FETCH_LIST_FAILED = "PRODUCTS_FETCH_LIST_FAILED";
export const PRODUCTS_CHANGE_SELECTED_PRODUCT = "PRODUCTS_CHANGE_SELECTED_PRODUCT";